### ISSUE TITLE
Add documentation for middleware

### ISSUE THREAD

**Issue by jdwuarin** [botmasterai/botmasterai.github.io#3]

**Comment by furenberger** [comment]
Hey, I was actually looking at doing this - but am not sure what to do to contribute for gitbook.

I set up a middleware (in a separate file) and was going to PR the plain HTML... but i don't think that is the preferred way.  

Do you suggest I clone/fork your repo, set it up as a new book and then PR from there?  I wish gitbook at the integration already...

**Comment by jdwuarin** [comment]
Hey, sorry for only getting back on this now.  I've updated the readme to explain how you would go about doing a proper PR for this documentation. Open up a new issue if that doesn't work for you.
